name: fingerfy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1
  leak_tracker_flutter_testing: ^3.0.5
  leak_tracker: ^10.0.4
  flutter_3d_controller: ^1.3.1
  android_intent_plus: ^4.0.3
  test_api: ^0.7.2
  meta: ^1.15.0
  http: ^1.2.2
  flutter_windowmanager: ^0.2.0
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  flutter_local_notifications: ^17.2.1+2
  shared_preferences: ^2.2.3
  # firebase_core: ^3.4.1  # Rimosso
  # firebase_auth: ^5.1.2  # Rimosso
  # cloud_firestore: ^5.1.0  # Rimosso
  # firebase_storage: ^12.1.1  # Rimosso
  # firebase_analytics: ^11.2.0  # Rimosso
  image_picker: ^1.1.2
  timezone: ^0.9.4
  flutter_plugin_android_lifecycle: ^2.0.20
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  logger: ^2.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/statua_invalid.png
    - assets/statua_attiva.png
    - assets/dock_circle.png
    - assets/dockbar.png
    - assets/emoji.png
    - assets/icona_posizione.png
    - assets/pallino_notifiche.png
    - assets/panning.png
    - assets/sezione_pod.png
    - assets/sezione_pod_active.png
    - assets/sezione_scroll.png
    - assets/sezione_scroll_active.png
    - assets/sezione_tap.png
    - assets/sezione_tap_active.png

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf
        - asset: assets/fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
          style: italic

    - family: KeplerStd
      fonts:
        - asset: assets/fonts/Kepler-Std-Light-Italic-Subhead.otf
        - asset: assets/fonts/Kepler-Std-Light-Italic-Subhead.otf
