// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALcu_0g-N7-f6s3Yl33JExh16DQ_CjCOo',
    appId: '1:152413743024:web:b4bd4df287dc6af7965875',
    messagingSenderId: '152413743024',
    projectId: 'fingerfy-ac6af',
    authDomain: 'fingerfy-ac6af.firebaseapp.com',
    storageBucket: 'fingerfy-ac6af.appspot.com',
    measurementId: 'G-ZSEWVD0VFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAksRKhSswNxqN1I6R2U0TBgnz2zyWEurI',
    appId: '1:152413743024:android:76f273fd205448ea965875',
    messagingSenderId: '152413743024',
    projectId: 'fingerfy-ac6af',
    storageBucket: 'fingerfy-ac6af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMvhB8xlkTUxe9Ln3djkOXM8zoUdk_S3o',
    appId: '1:152413743024:ios:c51da562d6b13057965875',
    messagingSenderId: '152413743024',
    projectId: 'fingerfy-ac6af',
    storageBucket: 'fingerfy-ac6af.appspot.com',
    iosBundleId: 'io.andreealavric.fingerfy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMvhB8xlkTUxe9Ln3djkOXM8zoUdk_S3o',
    appId: '1:152413743024:ios:c51da562d6b13057965875',
    messagingSenderId: '152413743024',
    projectId: 'fingerfy-ac6af',
    storageBucket: 'fingerfy-ac6af.appspot.com',
    iosBundleId: 'io.andreealavric.fingerfy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALcu_0g-N7-f6s3Yl33JExh16DQ_CjCOo',
    appId: '1:152413743024:web:c02d0faa116e4273965875',
    messagingSenderId: '152413743024',
    projectId: 'fingerfy-ac6af',
    authDomain: 'fingerfy-ac6af.firebaseapp.com',
    storageBucket: 'fingerfy-ac6af.appspot.com',
    measurementId: 'G-4M53B9WFXN',
  );
}
